require('globals')
require('keymaps')
require('plugins');

--require('plugins.lazy')
--require('plugins.lualine')
--require('plugins.noice')
-- require('plugins.misc')
-- require('options')
-- require('misc')
-- require('plugins.dap')
-- require('plugins.gitsigns')
-- require('plugins.tele')
-- require('plugins.treesitter')
-- require('plugins.lsp')
-- require('plugins.trouble')
-- require('plugins.obsidian')
-- require('plugins.zenmode')
-- require('plugins.neogit')
-- require('plugins.codesnap')
-- require('plugins.harpoon')
