#!/usr/bin/env sh

ARCH="$(uname -m | tr '[:upper:]' '[:lower:]')-$(uname -s | tr '[:upper:]' '[:lower:]')"
USER="$(id -un)"
HOME="$(realpath ~)"
HMGR="${HOME}/.config/hm"
KEYS="${HOME}/.config/sops/age/keys.txt"

# Check we have a personal flake containing profile settings

if [ ! -f "${HMGR}/flake.nix" ]; then
	echo "Personal flake missing!"
	echo "Please create something like that following in ${HMGR}/flake.nix ..."
	cat <<EOF

{
  description = "Personal Home Manager configuration";

  inputs = {
    hmgr.url = "github:///spoon68k/home-mgr?submodules=1";
  };

  outputs = { self, hmgr, ... }:
    {
      homeConfigurations = {
        <username> = hmgr.homeModule {
          username = "<username>";
          git-profile = "<profile>";
          gui-packages = false|true;
        };
      };
    };
}

EOF
	exit 1
fi

# Check we have private keys 

if [ -f "${KEYS}" ]; then
    permissions=$(stat -c "%a" "${KEYS}")
    if [ "$permissions" -ne 600 ]; then
        echo "'${KEYS}' exists, but does not have the correct permissions (owner=rw only)" >&2
	exit 1
    fi
else
    echo "'${KEYS}' does not exist" >&2
    exit 1
fi

# Process commands

if [ "$1" = "switch" ]; then

    cd "${HMGR}"
    nix flake update
    home-manager --flake ".#${USER}" switch

    if [ ! -f "${HOME}/.config/nvim/lazy-lock.json" ]; then
        echo "Creating lazy lock for nvim"
        cp "${HOME}/.config/nvim/lazy-lock-vcs.json" "${HOME}/.config/nvim/lazy-lock.json"
        chmod 644 "${HOME}/.config/nvim/lazy-lock.json"
    fi

elif [ "$1" = "generations" ]; then
	cd "${HMGR}"
	home-manager --flake ".#${USER}" generations | awk '{printf "\033[36m%4d\033[0m -> %s %s\n", $5, $1, $2}'

elif [ "$1" = "activate" ]; then
    if [ -n "$2" ]; then
        echo "Activating generation: $2"
        PKG=`home-manager --flake ".#${USER}" generations | awk -v gen_id="$2" '$5 == gen_id {print $7}'`
    	"${PKG}/activate"
    else
        echo "Error: 'activate' command requires an ID."
        echo "Usage: `basename $0` activate <id>"
        exit 1
    fi

else
    echo "Usage: `basename $0` {switch|generations|activate <id>}"
    exit 1
fi

exit 0

