#!/usr/bin/env sh

# This script allows me to work on nvim configuration (dev mode)

# -----------------------------------------------------------------------------

HOME="$(realpath ~)"
HMGR="${HOME}/workspace/home-mgr"

if [ ! -d "${HMGR}" ]; then
  echo "dev tree not found for home-mgr" >&2
  exit 1
fi

if [ ! -f "${HOME}/.config/nvim/README.md" ]; then
  echo "cannot find nvim config" >&2
  exit 1
fi

STATUS=$( ( realpath "${HOME}/.config/nvim/README.md" | grep -q '^/nix/store' ) && echo hm || echo dev )

# -----------------------------------------------------------------------------

if [ "$1" = "status" ]; then

    if [ "${STATUS}" = "hm" ]; then
        echo "status: home-manager mode"
    else
        echo "status: dev mode"
        diff -rx lazy-lock.json "${HOME}/.config/nvim" "${HMGR}/dotfiles/nvim"
    fi

elif [ "$1" = "dev" ]; then

  if [ "${STATUS}" = "hm" ]; then
    rm -rf "${HOME}/.config/nvim.bak"
    mv "${HOME}/.config/nvim" "${HOME}/.config/nvim.bak"
    rsync -avL "${HOME}/.config/nvim.bak/" "${HOME}/.config/nvim" 
    echo "switched: home-manager -> dev"
  else
    echo "already in dev mode"

  fi

else
    echo "Usage: `basename $0` {status|dev}"
    exit 1
fi
